version: "3"

services:
  db:
    image: mysql:8.0.35
    environment:
      SQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "your/machine/path/folder/must/empty:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3300:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
